name: taskmaster
description: Tasks evolved.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.2

environment:
  sdk: ">=3.0.0 <3.5.0"

dependencies:
  flutter:
    sdk: flutter
  datetime_picker_formfield: ^2.0.0
  http: ^0.13.3
  intl: ^0.19.0
  jiffy: ^6.3.1
  google_sign_in: ^5.0.7
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  flutter_app_badger: ^1.3.0
  timeago: ^3.1.0
  characters: ^1.1.0
  flutter_platform_widgets: ^2.0.0
  yaml: ^3.1.0
  json_annotation: ^4.9.0

  meta: '>=1.1.0 <2.0.0'
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_logging: ^0.5.1
  built_value: ^8.9.2
  built_collection: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  test: ^1.16.8
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  mockito: ^5.0.16
  build_runner: '>=1.0.0 <3.0.0'
  built_value_generator: ^8.9.2
  json_serializable: ^6.5.4

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/TaskMasterLogo.png"
  image_path_android: "assets/launcher/TaskMasterLogo.png"
  adaptive_icon_background: "assets/launcher/TaskMasterLogo_bg.png"
  adaptive_icon_foreground: "assets/launcher/TaskMasterLogo_fg.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
