// Mocks generated by Mockito 5.4.6 from annotations
// in taskmaster/test/core/services/task_completion_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:intl/intl.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:taskmaster/features/tasks/domain/task_repository.dart' as _i4;
import 'package:taskmaster/models/task_item.dart' as _i2;
import 'package:taskmaster/models/task_item_blueprint.dart' as _i6;
import 'package:taskmaster/models/task_recurrence.dart' as _i7;
import 'package:taskmaster/timezone_helper.dart' as _i8;
import 'package:timezone/timezone.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskItem_0 extends _i1.SmartFake implements _i2.TaskItem {
  _FakeTaskItem_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTZDateTime_1 extends _i1.SmartFake implements _i3.TZDateTime {
  _FakeTZDateTime_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i4.TaskRepository {
  @override
  _i5.Future<void> addTask(_i6.TaskItemBlueprint? blueprint) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [blueprint]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<({_i7.TaskRecurrence? recurrence, _i2.TaskItem taskItem})>
  updateTaskAndRecurrence(
    String? taskItemDocId,
    _i6.TaskItemBlueprint? blueprint,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskAndRecurrence, [
              taskItemDocId,
              blueprint,
            ]),
            returnValue:
                _i5.Future<
                  ({_i7.TaskRecurrence? recurrence, _i2.TaskItem taskItem})
                >.value((
                  recurrence: null,
                  taskItem: _FakeTaskItem_0(
                    this,
                    Invocation.method(#updateTaskAndRecurrence, [
                      taskItemDocId,
                      blueprint,
                    ]),
                  ),
                )),
            returnValueForMissingStub:
                _i5.Future<
                  ({_i7.TaskRecurrence? recurrence, _i2.TaskItem taskItem})
                >.value((
                  recurrence: null,
                  taskItem: _FakeTaskItem_0(
                    this,
                    Invocation.method(#updateTaskAndRecurrence, [
                      taskItemDocId,
                      blueprint,
                    ]),
                  ),
                )),
          )
          as _i5.Future<
            ({_i7.TaskRecurrence? recurrence, _i2.TaskItem taskItem})
          >);

  @override
  _i5.Future<void> deleteTask(_i2.TaskItem? taskItem) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskItem]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.TaskItem> toggleTaskCompletion(
    _i2.TaskItem? task, {
    required bool? complete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #toggleTaskCompletion,
              [task],
              {#complete: complete},
            ),
            returnValue: _i5.Future<_i2.TaskItem>.value(
              _FakeTaskItem_0(
                this,
                Invocation.method(
                  #toggleTaskCompletion,
                  [task],
                  {#complete: complete},
                ),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.TaskItem>.value(
              _FakeTaskItem_0(
                this,
                Invocation.method(
                  #toggleTaskCompletion,
                  [task],
                  {#complete: complete},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.TaskItem>);
}

/// A class which mocks [TimezoneHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimezoneHelper extends _i1.Mock implements _i8.TimezoneHelper {
  @override
  bool get timezoneInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#timezoneInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.Future<void> configureLocalTimeZone() =>
      (super.noSuchMethod(
            Invocation.method(#configureLocalTimeZone, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i3.TZDateTime getLocalTime(DateTime? dateTime) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalTime, [dateTime]),
            returnValue: _FakeTZDateTime_1(
              this,
              Invocation.method(#getLocalTime, [dateTime]),
            ),
            returnValueForMissingStub: _FakeTZDateTime_1(
              this,
              Invocation.method(#getLocalTime, [dateTime]),
            ),
          )
          as _i3.TZDateTime);

  @override
  String getFormattedLocalTime(DateTime? dateTime, String? format) =>
      (super.noSuchMethod(
            Invocation.method(#getFormattedLocalTime, [dateTime, format]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getFormattedLocalTime, [dateTime, format]),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#getFormattedLocalTime, [dateTime, format]),
            ),
          )
          as String);

  @override
  String getFormattedLocalTimeFromFormat(
    DateTime? dateTime,
    _i10.DateFormat? dateFormat,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFormattedLocalTimeFromFormat, [
              dateTime,
              dateFormat,
            ]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getFormattedLocalTimeFromFormat, [
                dateTime,
                dateFormat,
              ]),
            ),
            returnValueForMissingStub: _i9.dummyValue<String>(
              this,
              Invocation.method(#getFormattedLocalTimeFromFormat, [
                dateTime,
                dateFormat,
              ]),
            ),
          )
          as String);
}
