// Mocks generated by Mockito 5.4.6 from annotations
// in taskmaster/test/core/services/task_completion_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i6;
import 'package:intl/intl.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:taskmaster/core/database/app_database.dart' as _i4;
import 'package:taskmaster/core/services/analytics_service.dart' as _i15;
import 'package:taskmaster/core/services/sync_service.dart' as _i14;
import 'package:taskmaster/features/tasks/domain/task_repository.dart' as _i7;
import 'package:taskmaster/models/task_item.dart' as _i2;
import 'package:taskmaster/models/task_item_blueprint.dart' as _i9;
import 'package:taskmaster/models/task_recurrence.dart' as _i10;
import 'package:taskmaster/timezone_helper.dart' as _i11;
import 'package:timezone/timezone.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaskItem_0 extends _i1.SmartFake implements _i2.TaskItem {
  _FakeTaskItem_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTZDateTime_1 extends _i1.SmartFake implements _i3.TZDateTime {
  _FakeTZDateTime_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDatabase_2 extends _i1.SmartFake implements _i4.AppDatabase {
  _FakeAppDatabase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseFirestore_3 extends _i1.SmartFake
    implements _i5.FirebaseFirestore {
  _FakeFirebaseFirestore_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRef_4<State extends Object?> extends _i1.SmartFake
    implements _i6.Ref<State> {
  _FakeRef_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i7.TaskRepository {
  @override
  _i8.Future<void> addTask(_i9.TaskItemBlueprint? blueprint) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [blueprint]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<({_i10.TaskRecurrence? recurrence, _i2.TaskItem taskItem})>
  updateTaskAndRecurrence(
    String? taskItemDocId,
    _i9.TaskItemBlueprint? blueprint,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTaskAndRecurrence, [
              taskItemDocId,
              blueprint,
            ]),
            returnValue:
                _i8.Future<
                  ({_i10.TaskRecurrence? recurrence, _i2.TaskItem taskItem})
                >.value((
                  recurrence: null,
                  taskItem: _FakeTaskItem_0(
                    this,
                    Invocation.method(#updateTaskAndRecurrence, [
                      taskItemDocId,
                      blueprint,
                    ]),
                  ),
                )),
            returnValueForMissingStub:
                _i8.Future<
                  ({_i10.TaskRecurrence? recurrence, _i2.TaskItem taskItem})
                >.value((
                  recurrence: null,
                  taskItem: _FakeTaskItem_0(
                    this,
                    Invocation.method(#updateTaskAndRecurrence, [
                      taskItemDocId,
                      blueprint,
                    ]),
                  ),
                )),
          )
          as _i8.Future<
            ({_i10.TaskRecurrence? recurrence, _i2.TaskItem taskItem})
          >);

  @override
  _i8.Future<void> deleteTask(_i2.TaskItem? taskItem) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [taskItem]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.TaskItem> toggleTaskCompletion(
    _i2.TaskItem? task, {
    required bool? complete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #toggleTaskCompletion,
              [task],
              {#complete: complete},
            ),
            returnValue: _i8.Future<_i2.TaskItem>.value(
              _FakeTaskItem_0(
                this,
                Invocation.method(
                  #toggleTaskCompletion,
                  [task],
                  {#complete: complete},
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.TaskItem>.value(
              _FakeTaskItem_0(
                this,
                Invocation.method(
                  #toggleTaskCompletion,
                  [task],
                  {#complete: complete},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.TaskItem>);
}

/// A class which mocks [TimezoneHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimezoneHelper extends _i1.Mock implements _i11.TimezoneHelper {
  @override
  bool get timezoneInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#timezoneInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> configureLocalTimeZone() =>
      (super.noSuchMethod(
            Invocation.method(#configureLocalTimeZone, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i3.TZDateTime getLocalTime(DateTime? dateTime) =>
      (super.noSuchMethod(
            Invocation.method(#getLocalTime, [dateTime]),
            returnValue: _FakeTZDateTime_1(
              this,
              Invocation.method(#getLocalTime, [dateTime]),
            ),
            returnValueForMissingStub: _FakeTZDateTime_1(
              this,
              Invocation.method(#getLocalTime, [dateTime]),
            ),
          )
          as _i3.TZDateTime);

  @override
  String getFormattedLocalTime(DateTime? dateTime, String? format) =>
      (super.noSuchMethod(
            Invocation.method(#getFormattedLocalTime, [dateTime, format]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getFormattedLocalTime, [dateTime, format]),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#getFormattedLocalTime, [dateTime, format]),
            ),
          )
          as String);

  @override
  String getFormattedLocalTimeFromFormat(
    DateTime? dateTime,
    _i13.DateFormat? dateFormat,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFormattedLocalTimeFromFormat, [
              dateTime,
              dateFormat,
            ]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getFormattedLocalTimeFromFormat, [
                dateTime,
                dateFormat,
              ]),
            ),
            returnValueForMissingStub: _i12.dummyValue<String>(
              this,
              Invocation.method(#getFormattedLocalTimeFromFormat, [
                dateTime,
                dateFormat,
              ]),
            ),
          )
          as String);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i14.SyncService {
  @override
  _i4.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_2(this, Invocation.getter(#db)),
            returnValueForMissingStub: _FakeAppDatabase_2(
              this,
              Invocation.getter(#db),
            ),
          )
          as _i4.AppDatabase);

  @override
  _i5.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_3(
              this,
              Invocation.getter(#firestore),
            ),
            returnValueForMissingStub: _FakeFirebaseFirestore_3(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i5.FirebaseFirestore);

  @override
  _i6.Ref<Object?> get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _FakeRef_4<Object?>(this, Invocation.getter(#ref)),
            returnValueForMissingStub: _FakeRef_4<Object?>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i6.Ref<Object?>);

  @override
  _i8.Future<void> get initialPullComplete =>
      (super.noSuchMethod(
            Invocation.getter(#initialPullComplete),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> start(String? personDocId) =>
      (super.noSuchMethod(
            Invocation.method(#start, [personDocId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> pushPendingWrites({String? caller = 'unknown'}) =>
      (super.noSuchMethod(
            Invocation.method(#pushPendingWrites, [], {#caller: caller}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i15.AnalyticsService {
  @override
  bool get isEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isEnabled),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> setUserIdentifier(String? personDocId) =>
      (super.noSuchMethod(
            Invocation.method(#setUserIdentifier, [personDocId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logTaskCreated({bool? hasRecurrence = false}) =>
      (super.noSuchMethod(
            Invocation.method(#logTaskCreated, [], {
              #hasRecurrence: hasRecurrence,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logTaskCompleted({required bool? complete}) =>
      (super.noSuchMethod(
            Invocation.method(#logTaskCompleted, [], {#complete: complete}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logTaskDeleted() =>
      (super.noSuchMethod(
            Invocation.method(#logTaskDeleted, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logSprintCreated({required int? taskCount}) =>
      (super.noSuchMethod(
            Invocation.method(#logSprintCreated, [], {#taskCount: taskCount}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logScreenView(String? screenName) =>
      (super.noSuchMethod(
            Invocation.method(#logScreenView, [screenName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
