// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ZsBt4T6bFUUC-bbD8XHNm9zeTameeog',
    appId: '1:689103212710:web:df4ca9346b23702c76e467',
    messagingSenderId: '689103212710',
    projectId: 'm3-taskmaster-3000',
    authDomain: 'm3-taskmaster-3000.firebaseapp.com',
    databaseURL: 'https://m3-taskmaster-3000.firebaseio.com',
    storageBucket: 'm3-taskmaster-3000.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE2vhgb3xnwiicanE1LtA8QOFBJCUyT20',
    appId: '1:689103212710:android:94b4812f1f81b128',
    messagingSenderId: '689103212710',
    projectId: 'm3-taskmaster-3000',
    databaseURL: 'https://m3-taskmaster-3000.firebaseio.com',
    storageBucket: 'm3-taskmaster-3000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQQGWOrNNC7Yxoua058JLGGI4TMRxc-5U',
    appId: '1:689103212710:ios:7d0d83f33a916d2976e467',
    messagingSenderId: '689103212710',
    projectId: 'm3-taskmaster-3000',
    databaseURL: 'https://m3-taskmaster-3000.firebaseio.com',
    storageBucket: 'm3-taskmaster-3000.appspot.com',
    androidClientId: '689103212710-cqhurt503qhuot94s0cd7tdvkle5dd2k.apps.googleusercontent.com',
    iosClientId: '689103212710-h2qjrs3i1nioiqt71sl9v0o9jm9cmfv6.apps.googleusercontent.com',
    iosBundleId: 'com.mayhew3.taskmaster.flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQQGWOrNNC7Yxoua058JLGGI4TMRxc-5U',
    appId: '1:689103212710:ios:94b4812f1f81b128',
    messagingSenderId: '689103212710',
    projectId: 'm3-taskmaster-3000',
    databaseURL: 'https://m3-taskmaster-3000.firebaseio.com',
    storageBucket: 'm3-taskmaster-3000.appspot.com',
    androidClientId: '689103212710-cqhurt503qhuot94s0cd7tdvkle5dd2k.apps.googleusercontent.com',
    iosClientId: '689103212710-dt9knuqtsdl75li6sbakvcjn2ha040s3.apps.googleusercontent.com',
    iosBundleId: 'com.mayhew3.taskmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ZsBt4T6bFUUC-bbD8XHNm9zeTameeog',
    appId: '1:689103212710:web:537dd37086389ad476e467',
    messagingSenderId: '689103212710',
    projectId: 'm3-taskmaster-3000',
    authDomain: 'm3-taskmaster-3000.firebaseapp.com',
    databaseURL: 'https://m3-taskmaster-3000.firebaseio.com',
    storageBucket: 'm3-taskmaster-3000.appspot.com',
  );

}